version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-2-{{ checksum "package.json" }}-{{ checksum "package-lock.json"}}
            - node_modules-2-{{ checksum "package.json" }}
            - node_modules-2-
      - run:
          name: install
          command: npm ci
      - save_cache:
          paths:
            - $HOME/.npm
          key: node_modules-2-{{ checksum "package.json" }}-{{ checksum "package-lock.json"}}
      - run:
          name: test
          command: npm test
      - run:
          name: release
          command: npm run semantic-release || true
